version: '3.2'
services:

  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: rut3sql
       MYSQL_DATABASE: dockquiz
       MYSQL_USER: dockquiz
       MYSQL_PASSWORD: DockQuiz

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:rw
    env_file: env-local/.env
    ports:
      - "8003:80"
    links:
      - redis
      - mysql
    environment:
      TZ: America/Sao_Paulo
      LANG: pt_BR.UTF-8
      LANGUAGE: pt_BR.UTF-8
      LC_CTYPE: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
      LC_TIME: pt_BR.UTF-8

volumes:
  data:
